import React, { useState } from 'react';
import { 
  Banknote, 
  TrendingUp, 
  Calendar, 
  Calculator, 
  Check, 
  Copy, 
  FileSpreadsheet, 
  Map, 
  Info,
  DollarSign,
  Percent
} from 'lucide-react';

interface TariffRow {
  title: string;
  g2_5: number;
  g4: number;
  g6: number;
  g10: number;
  g16: number;
  g25: number;
  g40: number;
  g65: number;
}

const URBAN_DATA: TariffRow[] = [
  { 
    title: 'تعرفه حق‌الزحمه نظارت سامانه گاز روکار', 
    g2_5: 23530102, 
    g4: 27190340, 
    g6: 30556452, 
    g10: 33497715, 
    g16: 37746205, 
    g25: 43890176, 
    g40: 50491677, 
    g65: 70426902 
  },
  { 
    title: 'تعرفه حق‌الزحمه طراحی سامانه گاز روکار', 
    g2_5: 19251902, 
    g4: 22246642, 
    g6: 25000733, 
    g10: 27407221, 
    g16: 30883259, 
    g25: 35910144, 
    g40: 41311372, 
    g65: 57622011 
  },
  { 
    title: 'تعرفه حق‌الزحمه نظارت سامانه گاز توکار', 
    g2_5: 32942142, 
    g4: 38066476, 
    g6: 42779032, 
    g10: 46896800, 
    g16: 52844686, 
    g25: 61446245, 
    g40: 70688348, 
    g65: 98597662 
  },
  { 
    title: 'تعرفه حق‌الزحمه طراحی سامانه گاز توکار', 
    g2_5: 26952662, 
    g4: 31145298, 
    g6: 35001026, 
    g10: 38370109, 
    g16: 43236561, 
    g25: 50274201, 
    g40: 57835921, 
    g65: 80670814 
  },
  { 
    title: 'تعرفه بازرسی گاز آنکال (موارد قطعی گاز)، پرونده‌های گذشته و فیش مجدد', 
    g2_5: 7843367, 
    g4: 9063447, 
    g6: 10185483, 
    g10: 11165904, 
    g16: 12582068, 
    g25: 14630059, 
    g40: 16830559, 
    g65: 23475634 
  },
];

const RURAL_DATA: TariffRow[] = [
  { 
    title: 'تعرفه حق‌الزحمه نظارت سامانه گاز روکار', 
    g2_5: 28236122, 
    g4: 32628408, 
    g6: 36667742, 
    g10: 40197257, 
    g16: 45295446, 
    g25: 52668211, 
    g40: 60590013, 
    g65: 84512283 
  },
  { 
    title: 'تعرفه حق‌الزحمه طراحی سامانه گاز روکار', 
    g2_5: 23102282, 
    g4: 26695971, 
    g6: 30000880, 
    g10: 32888665, 
    g16: 37059911, 
    g25: 43092173, 
    g40: 49573647, 
    g65: 69146413 
  },
  { 
    title: 'تعرفه حق‌الزحمه نظارت سامانه گاز توکار', 
    g2_5: 39530571, 
    g4: 45679771, 
    g6: 51334838, 
    g10: 56276160, 
    g16: 63413623, 
    g25: 73735495, 
    g40: 84826017, 
    g65: 118317194 
  },
  { 
    title: 'تعرفه حق‌الزحمه طراحی سامانه گاز توکار', 
    g2_5: 32343194, 
    g4: 37374358, 
    g6: 42001231, 
    g10: 46044131, 
    g16: 51883874, 
    g25: 60329041, 
    g40: 69403105, 
    g65: 96804977 
  },
  { 
    title: 'تعرفه بازرسی گاز آنکال (موارد قطعی گاز)، پرونده‌های گذشته و فیش مجدد', 
    g2_5: 9412041, 
    g4: 10876136, 
    g6: 12222580, 
    g10: 13399085, 
    g16: 15098482, 
    g25: 17556070, 
    g40: 20196671, 
    g65: 28170760 
  },
];

export const PriceList: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'urban' | 'rural'>('urban');
  
  // Calculator states
  const [calcServiceType, setCalcServiceType] = useState<number>(0); // Index in rows
  const [calcMeterSize, setCalcMeterSize] = useState<keyof Omit<TariffRow, 'title'>>('g2_5');
  const [calcAddVat, setCalcAddVat] = useState<boolean>(true);
  const [isCopied, setIsCopied] = useState<boolean>(false);

  const formatPrice = (value: number) => {
    return value.toLocaleString('fa-IR');
  };

  const getMeterLabel = (key: string) => {
    switch(key) {
      case 'g2_5': return 'G2.5';
      case 'g4': return 'G4';
      case 'g6': return 'G6';
      case 'g10': return 'G10';
      case 'g16': return 'G16';
      case 'g25': return 'G25';
      case 'g40': return 'G40';
      case 'g65': return 'G65';
      default: return key.toUpperCase();
    }
  };

  const currentDataset = activeTab === 'urban' ? URBAN_DATA : RURAL_DATA;
  const currentCalcObj = currentDataset[calcServiceType];
  const basePrice = currentCalcObj ? currentCalcObj[calcMeterSize] : 0;
  const vatValue = calcAddVat ? Math.round(basePrice * 0.1) : 0;
  const totalPrice = basePrice + vatValue;

  const handleCopyCalc = () => {
    const textToCopy = `
⚙️ محاسبه تعرفه گاز رسانی (سال ۱۴۰۵)
──────────────────
🏢 نوع منطقه: ${activeTab === 'urban' ? 'شهری' : 'روستایی'}
📝 نوع خدمت: ${currentCalcObj.title}
📊 ظرفیت کنتور: ${getMeterLabel(calcMeterSize)}
💳 تعرفه پایه: ${formatPrice(basePrice)} تومان
➕ ارزش افزوده (۱۰٪): ${calcAddVat ? formatPrice(vatValue) + ' تومان' : 'تعلق نگرفته'}
💰 مبلغ قابل پرداخت: ${formatPrice(totalPrice)} تومان
──────────────────
Generated by Gazino App
    `.trim();

    navigator.clipboard.writeText(textToCopy);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2500);
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto px-1">
      
      {/* Premium Header Card */}
      <div className="bg-gradient-to-br from-blue-600 via-indigo-600 to-indigo-700 rounded-3xl p-5 text-white relative overflow-hidden shadow-xl shadow-blue-500/10">
        <div className="absolute top-0 right-0 w-80 h-80 bg-white/5 rounded-full -mr-40 -mt-20 blur-2xl"></div>
        <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-6 text-right">
          <div className="flex items-center gap-4">
            <div className="w-14 h-14 bg-white/10 backdrop-blur-md rounded-2xl flex items-center justify-center border border-white/20 shadow-inner shrink-0">
              <Banknote className="w-7 h-7 text-white" />
            </div>
            <div>
              <h3 className="text-xl font-black">تعرفه خدمات گازرسانی ۱۴۰۵ (استان آذربایجانغربی)</h3>
              <p className="text-blue-100 text-xs mt-1 leading-relaxed">
                مصوبه نظارت و طراحی پرونده‌های گازرسانی کشور - خدمات مسکونی، تجاری و صنعتی بدون محاسبه ارزش افزوده بر مبنای ریال
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Main Tabs and Table Container */}
      <div className="bg-white rounded-3xl border border-slate-200/80 shadow-md overflow-hidden">
        
        {/* Toggle Headings */}
        <div className="bg-slate-50 border-b border-slate-100 p-2.5 flex flex-col sm:flex-row justify-between items-center gap-3">
          <div className="flex items-center gap-2 shrink-0">
            <FileSpreadsheet className="w-4.5 h-4.5 text-slate-550" />
            <span className="text-xs font-black text-slate-700">نوع تعرفه را انتخاب کنید:</span>
          </div>

          <div className="flex bg-slate-200/60 p-1 rounded-2xl w-full sm:w-auto">
            <button
              onClick={() => { setActiveTab('urban'); }}
              className={`flex-1 sm:flex-none flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl text-xs font-black transition-all ${
                activeTab === 'urban'
                  ? 'bg-blue-600 text-white shadow-md'
                  : 'text-slate-600 hover:text-slate-900 hover:bg-slate-300/40'
              }`}
            >
              <Map className="w-4 h-4" />
              <span>تعرفه مناطق شهری</span>
            </button>
            <button
              onClick={() => { setActiveTab('rural'); }}
              className={`flex-1 sm:flex-none flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl text-xs font-black transition-all ${
                activeTab === 'rural'
                  ? 'bg-blue-600 text-white shadow-md'
                  : 'text-slate-600 hover:text-slate-900 hover:bg-slate-300/40'
              }`}
            >
              <Map className="w-4 h-4" />
              <span>تعرفه مناطق روستایی</span>
            </button>
          </div>
        </div>

        {/* Dynamic Title */}
        <div className="px-6 py-4 bg-slate-550/5 border-b border-slate-100 flex items-center gap-2.5">
          <TrendingUp className="w-4.5 h-4.5 text-blue-600 shrink-0" />
          <h4 className="font-extrabold text-[13px] text-slate-800 leading-normal">
            {activeTab === 'urban' 
              ? 'جدول تعرفه خدمات نظارت و طراحی سامانه های گازرسانی سال ۱۴۰۵ - بدون ارزش افزوده (شهری)'
              : 'جدول تعرفه پیشنهادی خدمات نظارت و طراحی سامانه های گازرسانی سال ۱۴۰۵ روستایی - بدون ارزش افزوده'
            }
          </h4>
        </div>

        {/* Table representation */}
        <div className="overflow-x-auto custom-scrollbar">
          <table className="w-full text-right border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-150 text-[10.5px] lg:text-[11px]">
                <th className="px-2.5 py-2.5 font-black text-slate-500 border-l border-slate-150 sticky right-0 bg-slate-50 z-25 min-w-[140px] sm:min-w-[185px] max-w-[210px]">شرح خدمات</th>
                {['g2_5', 'g4', 'g6', 'g10', 'g16', 'g25', 'g40', 'g65'].map((sz) => (
                  <th key={sz} className="px-2 py-2.5 font-black text-slate-500 text-center border-l border-slate-100 bg-slate-50/70 min-w-[70px] sm:min-w-[85px] tracking-tight">
                    {getMeterLabel(sz)}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-[10.5px]">
              {currentDataset.map((row, index) => (
                <tr key={index} className="group hover:bg-blue-50/30 transition-colors">
                  <td className="px-2.5 py-2.5 font-bold text-slate-755 border-l border-slate-150 sticky right-0 bg-white group-hover:bg-blue-50/10 z-20 shadow-[2px_0_5px_rgba(0,0,0,0.02)] transition-colors leading-[1.3] min-w-[140px] sm:min-w-[185px] max-w-[210px] break-words whitespace-normal font-sans">
                    {row.title}
                  </td>
                  {['g2_5', 'g4', 'g6', 'g10', 'g16', 'g25', 'g40', 'g65'].map((sz) => {
                    const priceVal = row[sz as keyof Omit<TariffRow, 'title'>];
                    return (
                      <td key={sz} className="px-2 py-2.5 text-center font-mono font-extrabold text-slate-700 ltr bg-white/40 group-hover:bg-transparent" dir="ltr">
                        {priceVal.toLocaleString()}
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="bg-blue-50/40 p-4 border-t border-slate-150 flex items-start gap-3">
          <Info className="w-5 h-5 text-blue-500 shrink-0 mt-0.5" />
          <p className="text-[11px] text-slate-650 leading-relaxed font-bold">
            در جدول‌های فوق کلیه ارقام حق‌الزحمه بدون احتساب ۱۰٪ قانون ارزش افزوده می‌باشد. جهت محاسبه نهائی تعرفه‌ها همراه با مالیات بر ارزش افزوده و سادگی کار، می‌توانید از ماشین‌حساب تعرفه زیر استفاده کنید.
          </p>
        </div>
      </div>

      {/* Dynamic Widget: Calculator */}
      <div className="bg-white rounded-3xl border border-slate-200/80 p-6 md:p-8 shadow-md">
        <div className="flex items-center gap-3 mb-6 border-b border-slate-100 pb-4">
          <div className="w-10 h-10 bg-amber-50 rounded-xl flex items-center justify-center text-amber-500 shrink-0">
            <Calculator className="w-5 h-5" />
          </div>
          <div>
            <h4 className="font-black text-slate-800 text-[15px]">ماشین‌حساب هوشمند محاسبه تعرفه گازرسانی</h4>
            <p className="text-[11px] text-slate-400 font-bold mt-0.5">محاسبه سریع سهم خدمات نظارت و طراحی کنتور با احتساب مالیات بر ارزش افزوده</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-start">
          
          {/* Controls - Left Column (7 cols) */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 md:col-span-7">
            
            {/* Tariff Category */}
            <div className="space-y-1.5 col-span-1 sm:col-span-2">
              <label className="text-xs font-black text-slate-500 dark:text-zinc-400 block">انتخاب دسته منطقه خدمات</label>
              <div className="grid grid-cols-2 gap-2 bg-slate-100 p-1.5 rounded-xl border border-slate-200/50">
                <button
                  onClick={() => { setActiveTab('urban'); }}
                  className={`py-2 px-3 rounded-lg text-xs font-extrabold transition-all text-center ${
                    activeTab === 'urban' 
                      ? 'bg-white shadow-sm text-blue-600 border border-slate-200' 
                      : 'text-slate-600 hover:bg-white/40'
                  }`}
                >
                  پروژه شهری
                </button>
                <button
                  onClick={() => { setActiveTab('rural'); }}
                  className={`py-2 px-3 rounded-lg text-xs font-extrabold transition-all text-center ${
                    activeTab === 'rural' 
                      ? 'bg-white shadow-sm text-blue-600 border border-slate-200' 
                      : 'text-slate-600 hover:bg-white/40'
                  }`}
                >
                  پروژه روستایی
                </button>
              </div>
            </div>

            {/* Service Selection */}
            <div className="space-y-1.5 col-span-1 sm:col-span-2">
              <label className="text-xs font-black text-slate-500 block">نوع خدمت گازرسانی</label>
              <select
                value={calcServiceType}
                onChange={(e) => setCalcServiceType(parseInt(e.target.value))}
                className="w-full bg-white border border-slate-200/80 rounded-xl px-3.5 py-3 text-xs font-extrabold text-slate-700 outline-none focus:border-blue-600 focus:ring-1 focus:ring-blue-600 transition-all select-none"
              >
                {currentDataset.map((row, i) => (
                  <option key={i} value={i}>
                    {row.title}
                  </option>
                ))}
              </select>
            </div>

            {/* Meter size selection */}
            <div className="space-y-1.5">
              <label className="text-xs font-black text-slate-500 block">ظرفیت کنتور (مترمکعب/ساعت)</label>
              <select
                value={calcMeterSize}
                onChange={(e) => setCalcMeterSize(e.target.value as keyof Omit<TariffRow, 'title'>)}
                className="w-full bg-white border border-slate-200/80 rounded-xl px-3.5 py-3 text-xs font-black text-slate-700 outline-none focus:border-blue-600 focus:ring-1 focus:ring-blue-600 transition-all font-mono"
              >
                <option value="g2_5">G2.5</option>
                <option value="g4">G4</option>
                <option value="g6">G6</option>
                <option value="g10">G10</option>
                <option value="g16">G16</option>
                <option value="g25">G25</option>
                <option value="g40">G40</option>
                <option value="g65">G65</option>
              </select>
            </div>

            {/* Tax value boolean toggler */}
            <div className="space-y-1.5">
              <label className="text-xs font-black text-slate-500 block">ارزش افزوده قانون مصوب (۱۰٪)</label>
              <button
                onClick={() => setCalcAddVat(!calcAddVat)}
                className={`w-full py-3 px-3.5 rounded-xl border text-xs font-black flex items-center justify-between transition-all ${
                  calcAddVat 
                    ? 'border-green-200 bg-green-50/55 text-green-700' 
                    : 'border-slate-200 bg-slate-50 text-slate-400'
                }`}
              >
                <span className="flex items-center gap-1.5">
                  <Percent className="w-3.5 h-3.5" />
                  <span>محاسبه ارزش افزوده</span>
                </span>
                <span className="text-[10px] bg-white border border-current px-2 py-0.5 rounded-md">
                  {calcAddVat ? 'فعال' : 'غیرفعال'}
                </span>
              </button>
            </div>

          </div>

          {/* Results Visual Sheet - Right Column (5 cols) */}
          <div className="bg-slate-50 rounded-2xl p-5 border border-slate-150 md:col-span-12 lg:col-span-5 flex flex-col justify-between self-stretch">
            <div className="space-y-4">
              <div className="text-slate-400 font-extrabold text-[10px] tracking-widest uppercase text-center pb-2 border-b border-slate-200/80">
                برگه رسید محاسباتی سیستم
              </div>

              {/* Row: Area */}
              <div className="flex items-center justify-between text-xs">
                <span className="font-bold text-slate-400">محدوده شهری/روستایی:</span>
                <span className="font-extrabold text-blue-600 px-2 py-0.5 bg-blue-50 rounded">
                  {activeTab === 'urban' ? 'شهری (پایه)' : 'روستایی (+ضریب پیشنهادی)'}
                </span>
              </div>

              {/* Row: Meter */}
              <div className="flex items-center justify-between text-xs font-bold text-slate-600">
                <span>سایز کنتور منتخب:</span>
                <span className="font-mono text-slate-800">{getMeterLabel(calcMeterSize)}</span>
              </div>

              {/* Divider */}
              <div className="border-t border-slate-200/60 my-2"></div>

              {/* Base price row */}
              <div className="flex items-center justify-between text-xs font-medium text-slate-550">
                <span>تعرفه پایه مصوب:</span>
                <div className="flex items-baseline gap-1">
                  <span className="font-mono font-black text-slate-700 text-sm">{formatPrice(basePrice)}</span>
                  <span className="text-[10px]">ریال</span>
                </div>
              </div>

              {/* Vat Price Row */}
              <div className="flex items-center justify-between text-xs font-medium text-slate-550">
                <span>مالیات ارزش افزوده (۱۰٪):</span>
                <div className="flex items-baseline gap-1">
                  <span className="font-mono font-black text-slate-700 text-sm">
                    {calcAddVat ? formatPrice(vatValue) : '۰'}
                  </span>
                  <span className="text-[10px]">ریال</span>
                </div>
              </div>

              {/* Grand total large wrapper */}
              <div className="bg-white rounded-xl p-4.5 border border-slate-200 flex flex-col items-center justify-center text-center mt-3 shadow-inner">
                <span className="text-[10px] font-black text-slate-400 mb-1">جمع کل قابل پرداخت پرونده گازرسانی</span>
                <div className="flex items-baseline gap-1 pb-1">
                  <span className="text-2xl font-black text-blue-600 font-mono tracking-tight">{formatPrice(totalPrice)}</span>
                  <span className="text-[11px] font-extrabold text-slate-500">ریال</span>
                </div>
                <div className="text-[9.5px] font-bold text-slate-400">
                  معادل {formatPrice(Math.round(totalPrice / 10))} تومان
                </div>
              </div>
            </div>

            {/* Direct copy handle button */}
            <button
              onClick={handleCopyCalc}
              className={`w-full py-2.5 px-4 rounded-xl font-black text-xs flex items-center justify-center gap-2 mt-4 transition-all active:scale-95 border cursor-pointer ${
                isCopied 
                  ? 'bg-green-600 border-green-600 text-white shadow-md' 
                  : 'bg-slate-800 border-slate-800 text-white hover:bg-slate-900 shadow-sm'
              }`}
            >
              {isCopied ? (
                <>
                  <Check className="w-4 h-4 text-white animate-bounce" />
                  <span>محاسبات کپی شد!</span>
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 text-slate-300" />
                  <span>کپی رسید محاسبات تعرفه</span>
                </>
              )}
            </button>
          </div>

        </div>
      </div>

    </div>
  );
};
